config/routes.rb
Rails.application.routes.draw do

  # resources :posts do
  #   resources :comments
  # end

  get '/posts', to: 'posts#index'
  get '/posts/new', to: 'posts#new', as: 'new_post'
  post '/posts', to: 'posts#create'
  get '/posts/:id', to: 'posts#show', as: 'post'
  get '/posts/:id/edit', to: 'posts#edit', as: 'edit_post'
  patch '/posts/:id', to: 'posts#update'
  delete '/posts/:id', to: 'posts#destroy'
  
  get '/posts/:post_id/comments', to: 'comments#index', as: 'post_comments'
  get '/posts/:post_id/comments/new', to: 'comments#new'
  post '/posts/:post_id/comments', to: 'comments#create'
  

  root "posts#index"

  get '/about', to: 'pages#about'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'signup' => 'users#new'
  post '/users' => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  has_many :posts
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all.order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/signup'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment-content">
    <p class="comment-name"><strong><%= comment.name %></strong></p>
    <p class="comment-body"><%= comment.body %></p>
    <p class="comment-time"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>

  <% if @post.user == current_user %>
  <p><%= link_to 'Delete', [comment.post, comment],
                            method: :delete,
                            data: {confirm: "Are you sure?"} %></p>
  <% end %>

</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p><br>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StevenUniverseBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
        <%= image_tag("steven-universe-logo.svg", height: '65.1', width: '220') %>
      <% end %>
    </div>
      <ul>
        <li class="category">Website</li>
        <li><%= link_to "Blog", root_path %></li>
        <li><%= link_to "About", about_path %></li>
                <% if current_user %>
        <li>Signed in as <%= current_user.name %></li>
        <li><%= link_to "Logout", '/logout' %></li>
        <% else %>
        <li><%= link_to 'Login', '/login' %></li>
        <li><%= link_to 'Signup', '/signup' %></li>
        <% end %>
      </ul>

      <p class="sign-in">Admin Login</p>
    </div>

    <div id="main-content">
      <div id="header">
        <% if current_user %>
        Signed in as <%= current_user.name %>
        | <%= link_to "Logout", '/logout' %>
        <% else %>
        <%= link_to 'Login', '/login' %>
        | <%= link_to 'Signup', '/signup' %>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="page-wrapper">

  <%= image_tag("steven-universe-cast.png") %>

  <p>This is a blog about the wonderful show called <em>Steven Universe</em>.</p>

  <p><em>Steven Universe</em> is a show created by the amazing and talented Rebecca Sugar. It is about a boy named Steven Universe and his three moms: Garnet, Pearl, and Amethyst. Together they are called the Crystal Gems.</p>

  <p>Gems are intergalactic beings (or aliens if you want to sound less cool) who are the physical manifestations of gemstones. Gems are a race entirely composed of women, and their bodies are made from light. Steven is half-human and is the only male gem to have ever existed.</p>

  <p>Gems have magical abilities. They each have a gemstone on their bodies from which they can summon their weapons or shapeshift. They may even fuse, which involves a dance to make them in sync and shifting their bodies into light so that their bodies merge.</p>

  <p>Steven's mother, Rose Quartz, was the leader of the Crystal gems. She led the Crystal Gems to fight off their home planet who were attempting to invade Earth.</p>

  <p>Thousands of years after the invasion attempt, Rose Quartz met Steven's father Greg Universe. Rose Quartz decided to give up her physical form in order to give life, and thus Steven was born. Much of the show's themes stem from Rose Quartz's death, with Steven and the Crystal Gems dealing with Rose Quartz's decision and learning about the many things that she never told them before she died.</p>

  <p>In addition to the amazing storytelling are amazing songs written by Rebecca Sugar, as well as LGBTQ themes. It is one of the very few shows that has queer characters in the spotlight.</p>

  <p>If you love <em>Steven Universe</em> please join my blog! If you don't, please watch <em>Steven Universe</em> before it ends in 2018 😩</p>

</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
  <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
  <ul>
    <% @post.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div class="page-wrapper">
  <h1>Edit Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<div class="page-wrapper">
  <%= link_to "New Post", new_post_path %>

  <% @posts.each do |post| %>
    <div class="post_wrapper">
      <h2 class="title"><%= link_to post.title, post %></h2>
      <p class="date"><%= post.created_at.strftime("%B, %d, %Y") %></p>
    </div>

  <% end %>

</div>

app/views/posts/new.html.erb
<div class="page-wrapper">
  <h1>Write a New Post</h1>

  <%= render 'form' %>
</div>

app/views/posts/show.html.erb
<div class="post-wrapper">

  <h1 class="title">
    <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago
    | Posted by <%= @post.user.name %> <br>
    <% if @post.user == current_user %>
      <%= link_to "Edit", edit_post_path(@post) %>
      | <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"} %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body %>
  </p>

  <div id="comments">
    <h2 class="title"><%= @post.comments.count %> Comments</h2>
    <p class="body">
    <%= render @post.comments %>
    </p>
    <h3>Add a comment</h3>
    <%= render 'comments/form' %>
  </div>
</div>

app/views/users/new.html.erb
<div class="page-wrapper">

  <h2>Sign Up</h2>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %><br>
  Email: <%= f.text_field :email %><br>
  Password: <%= f.password_field :password %><br>
  Password Confirmation: <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Submit" %>

<% end %>
</div>